export type QuizOption = {
  id: "A" | "B" | "C" | "D";
  text: string;
};

export type QuizQuestion = {
  id: string;
  number: number;
  level: string;
  question: string;
  options: QuizOption[];
  correctOptionId: QuizOption["id"];
};

export const POINTS_PER_QUESTION = 10;
export const QUESTIONS_PER_ATTEMPT = 10;

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: "q01",
    number: 1,
    level: "L1",
    question: "What does the 'E' in ESG stand for?",
    options: [
      { id: "A", text: "Efficiency" },
      { id: "B", text: "Environment" },
      { id: "C", text: "Employment" },
      { id: "D", text: "Ethics" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q02",
    number: 2,
    level: "L1",
    question: "Which action supports workplace safety?",
    options: [
      { id: "A", text: "Ignoring a spill" },
      { id: "B", text: "Using the correct PPE" },
      { id: "C", text: "Blocking emergency exits" },
      { id: "D", text: "Removing machine guards" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q03",
    number: 3,
    level: "L1",
    question: "Which document normally guides ethical behaviour in a company?",
    options: [
      { id: "A", text: "Canteen menu" },
      { id: "B", text: "Code of Conduct" },
      { id: "C", text: "Visitor pass" },
      { id: "D", text: "Shift roster" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q04",
    number: 4,
    level: "L1",
    question: "Which bin should generally be used for recyclable paper waste?",
    options: [
      { id: "A", text: "Food waste bin" },
      { id: "B", text: "Hazardous waste bin" },
      { id: "C", text: "Recyclable waste bin" },
      { id: "D", text: "Medical waste bin" },
    ],
    correctOptionId: "C",
  },
  {
    id: "q05",
    number: 5,
    level: "L1",
    question: "Which of the following is an example of diversity and inclusion?",
    options: [
      { id: "A", text: "Giving equal respect to all employees" },
      { id: "B", text: "Allowing only one group to speak" },
      { id: "C", text: "Ignoring employee concerns" },
      { id: "D", text: "Making jokes about background or language" },
    ],
    correctOptionId: "A",
  },
  {
    id: "q06",
    number: 6,
    level: "L1",
    question: "Which action helps reduce electricity consumption?",
    options: [
      { id: "A", text: "Keeping lights on in empty rooms" },
      { id: "B", text: "Switching off unused equipment" },
      { id: "C", text: "Running AC with doors open" },
      { id: "D", text: "Using compressed air for cleaning clothes" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q07",
    number: 7,
    level: "L1",
    question: "What should an employee do if asked to hide incorrect data?",
    options: [
      { id: "A", text: "Accept it silently" },
      { id: "B", text: "Report it through the proper channel" },
      { id: "C", text: "Delete the records" },
      { id: "D", text: "Blame another team" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q08",
    number: 8,
    level: "L1",
    question: "Which action supports human rights at work?",
    options: [
      { id: "A", text: "Forced overtime without consent" },
      { id: "B", text: "Respectful treatment of all workers" },
      { id: "C", text: "Discrimination in job allocation" },
      { id: "D", text: "Withholding wages" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q09",
    number: 9,
    level: "L1",
    question: "Which of these is a greenhouse gas?",
    options: [
      { id: "A", text: "Oxygen" },
      { id: "B", text: "Nitrogen" },
      { id: "C", text: "Carbon dioxide" },
      { id: "D", text: "Argon" },
    ],
    correctOptionId: "C",
  },
  {
    id: "q10",
    number: 10,
    level: "L1",
    question: "What is a conflict of interest?",
    options: [
      { id: "A", text: "A safety drill" },
      { id: "B", text: "A situation where personal interest may affect business judgement" },
      { id: "C", text: "A quality inspection" },
      { id: "D", text: "A training attendance sheet" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q11",
    number: 11,
    level: "L1",
    question: "Which action reduces water wastage?",
    options: [
      { id: "A", text: "Reporting leakage immediately" },
      { id: "B", text: "Leaving taps open" },
      { id: "C", text: "Using water to clean dry dust unnecessarily" },
      { id: "D", text: "Ignoring overflow" },
    ],
    correctOptionId: "A",
  },
  {
    id: "q12",
    number: 12,
    level: "L1",
    question: "Which behaviour shows respect at the workplace?",
    options: [
      { id: "A", text: "Listening without interrupting" },
      { id: "B", text: "Using abusive language" },
      { id: "C", text: "Mocking a colleague" },
      { id: "D", text: "Sharing personal data without permission" },
    ],
    correctOptionId: "A",
  },
  {
    id: "q13",
    number: 13,
    level: "L1",
    question: "Why is accurate record keeping important?",
    options: [
      { id: "A", text: "It improves canteen variety" },
      { id: "B", text: "It supports transparency and auditability" },
      { id: "C", text: "It reduces attendance" },
      { id: "D", text: "It avoids training" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q14",
    number: 14,
    level: "L1",
    question: "Which is the best basic action to control waste?",
    options: [
      { id: "A", text: "Mix all waste together" },
      { id: "B", text: "Segregate waste at source" },
      { id: "C", text: "Burn waste openly" },
      { id: "D", text: "Store waste near drains" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q15",
    number: 15,
    level: "L1",
    question: "Which of the following is a near miss?",
    options: [
      { id: "A", text: "An unsafe event that could have caused injury but did not" },
      { id: "B", text: "A completed monthly report" },
      { id: "C", text: "A planned audit" },
      { id: "D", text: "A successful production target" },
    ],
    correctOptionId: "A",
  },
  {
    id: "q16",
    number: 16,
    level: "L1",
    question: "Who is responsible for following company policies?",
    options: [
      { id: "A", text: "Only senior management" },
      { id: "B", text: "Only security staff" },
      { id: "C", text: "All employees and contractors" },
      { id: "D", text: "Only finance department" },
    ],
    correctOptionId: "C",
  },
  {
    id: "q17",
    number: 17,
    level: "L1",
    question: "Which of these is an example of air pollution control?",
    options: [
      { id: "A", text: "Using dust extraction system" },
      { id: "B", text: "Opening all chemical containers" },
      { id: "C", text: "Burning scrap material" },
      { id: "D", text: "Running diesel engines indoors without ventilation" },
    ],
    correctOptionId: "A",
  },
  {
    id: "q18",
    number: 18,
    level: "L2",
    question: "A machine is consuming more compressed air than usual because of leakage. What should you do?",
    options: [
      { id: "A", text: "Ignore it because production is running" },
      { id: "B", text: "Report and get the leak repaired" },
      { id: "C", text: "Increase compressor pressure" },
      { id: "D", text: "Cover the leak with tape without informing anyone" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q19",
    number: 19,
    level: "L2",
    question: "A contract worker is not wearing required PPE in a process area. What is the correct response?",
    options: [
      { id: "A", text: "Ignore because he is not your team member" },
      { id: "B", text: "Stop and guide him to wear correct PPE before work" },
      { id: "C", text: "Take a photo and circulate it publicly" },
      { id: "D", text: "Allow work if the task is short" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q20",
    number: 20,
    level: "L2",
    question: "A vendor offers a personal gift to speed up approval. What should you do?",
    options: [
      { id: "A", text: "Accept it if the value is small" },
      { id: "B", text: "Declare it and follow company gift policy" },
      { id: "C", text: "Ask for a bigger gift" },
      { id: "D", text: "Approve the vendor without documentation" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q21",
    number: 21,
    level: "L2",
    question: "Which KPI is most directly connected with climate impact?",
    options: [
      { id: "A", text: "Training attendance" },
      { id: "B", text: "Scope 1 and Scope 2 emissions" },
      { id: "C", text: "Canteen feedback score" },
      { id: "D", text: "Visitor count" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q22",
    number: 22,
    level: "L2",
    question: "Which practice supports fair labour standards?",
    options: [
      { id: "A", text: "Equal wages for equal work as per policy and law" },
      { id: "B", text: "Delaying payment to temporary workers" },
      { id: "C", text: "Denying rest breaks" },
      { id: "D", text: "Using child labour in low-risk work" },
    ],
    correctOptionId: "A",
  },
  {
    id: "q23",
    number: 23,
    level: "L2",
    question: "What is the purpose of a whistleblower mechanism?",
    options: [
      { id: "A", text: "To punish all complaints automatically" },
      { id: "B", text: "To allow reporting of unethical or illegal conduct safely" },
      { id: "C", text: "To replace HR processes completely" },
      { id: "D", text: "To share production targets" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q24",
    number: 24,
    level: "L2",
    question: "Which action is best before disposing of used oil?",
    options: [
      { id: "A", text: "Pour it into a drain" },
      { id: "B", text: "Mix it with general waste" },
      { id: "C", text: "Store it in labelled containers and hand over to authorised disposal agency" },
      { id: "D", text: "Burn it in open area" },
    ],
    correctOptionId: "C",
  },
  {
    id: "q25",
    number: 25,
    level: "L2",
    question: "A team member reports harassment. What should be the first correct approach?",
    options: [
      { id: "A", text: "Ignore unless there are witnesses" },
      { id: "B", text: "Handle it sensitively and escalate through the defined process" },
      { id: "C", text: "Discuss it openly in a group" },
      { id: "D", text: "Tell the person to adjust" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q26",
    number: 26,
    level: "L2",
    question: "Which action improves governance in procurement?",
    options: [
      { id: "A", text: "Single-person approval without records" },
      { id: "B", text: "Transparent vendor evaluation and documented approval" },
      { id: "C", text: "Choosing relatives as vendors without disclosure" },
      { id: "D", text: "Skipping purchase policy for urgent work" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q27",
    number: 27,
    level: "L2",
    question: "Which option shows better lifecycle thinking?",
    options: [
      { id: "A", text: "Buying low-cost material that creates high waste" },
      { id: "B", text: "Choosing durable material with lower environmental impact" },
      { id: "C", text: "Ignoring packaging waste" },
      { id: "D", text: "Selecting only based on fastest delivery" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q28",
    number: 28,
    level: "L2",
    question: "What should be included in a good community engagement activity?",
    options: [
      { id: "A", text: "Actual local need assessment" },
      { id: "B", text: "Only photo documentation" },
      { id: "C", text: "No communication with stakeholders" },
      { id: "D", text: "Unplanned donation without follow-up" },
    ],
    correctOptionId: "A",
  },
  {
    id: "q29",
    number: 29,
    level: "L2",
    question: "Why are internal audits important in ESG?",
    options: [
      { id: "A", text: "They replace legal compliance" },
      { id: "B", text: "They help verify compliance, gaps and corrective actions" },
      { id: "C", text: "They are only for finance teams" },
      { id: "D", text: "They remove the need for training" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q30",
    number: 30,
    level: "L2",
    question: "A chemical container has no label. What is the correct action?",
    options: [
      { id: "A", text: "Use it based on smell" },
      { id: "B", text: "Relabel or quarantine it as per procedure before use" },
      { id: "C", text: "Pour it into another container" },
      { id: "D", text: "Keep it near general waste" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q31",
    number: 31,
    level: "L2",
    question: "Which action supports employee wellbeing?",
    options: [
      { id: "A", text: "Ignoring fatigue signs" },
      { id: "B", text: "Encouraging reporting of fatigue and managing workload" },
      { id: "C", text: "Increasing overtime without review" },
      { id: "D", text: "Removing rest breaks to meet targets" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q32",
    number: 32,
    level: "L2",
    question: "Which is a sign of good data governance?",
    options: [
      { id: "A", text: "Changing data after submission without approval" },
      { id: "B", text: "Maintaining traceable, accurate and approved records" },
      { id: "C", text: "Keeping records only verbally" },
      { id: "D", text: "Using personal email for official approvals" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q33",
    number: 33,
    level: "L2",
    question: "Which waste should normally be treated as hazardous?",
    options: [
      { id: "A", text: "Clean cardboard" },
      { id: "B", text: "Food waste" },
      { id: "C", text: "Used chemical contaminated cloth" },
      { id: "D", text: "Office paper" },
    ],
    correctOptionId: "C",
  },
  {
    id: "q34",
    number: 34,
    level: "L3",
    question: "A department reports lower energy consumption this month, but production volume also reduced by 30%. Which indicator gives a more meaningful view?",
    options: [
      { id: "A", text: "Total electricity bill only" },
      { id: "B", text: "Energy intensity such as kWh per unit produced" },
      { id: "C", text: "Number of lights installed" },
      { id: "D", text: "Monthly attendance" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q35",
    number: 35,
    level: "L3",
    question: "A supplier has strong pricing but weak labour compliance records. What is the best ESG-aligned decision?",
    options: [
      { id: "A", text: "Select them because cost is lowest" },
      { id: "B", text: "Ignore social compliance if delivery is fast" },
      { id: "C", text: "Evaluate risk, require corrective action, and follow supplier due diligence process" },
      { id: "D", text: "Split the order without documentation" },
    ],
    correctOptionId: "C",
  },
  {
    id: "q36",
    number: 36,
    level: "L3",
    question: "Which scenario is a clear example of greenwashing risk?",
    options: [
      { id: "A", text: "Publishing verified emission reduction data" },
      { id: "B", text: "Claiming a product is eco-friendly without evidence" },
      { id: "C", text: "Reporting energy saving with calculation method" },
      { id: "D", text: "Using third-party certification" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q37",
    number: 37,
    level: "L3",
    question: "A safety target is achieved, but workers say near misses are not reported due to fear of blame. What is the biggest ESG concern?",
    options: [
      { id: "A", text: "Production planning" },
      { id: "B", text: "Under-reporting and weak safety culture" },
      { id: "C", text: "High training cost" },
      { id: "D", text: "Excessive documentation" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q38",
    number: 38,
    level: "L3",
    question: "During an ESG audit, a manager asks the team to show only selected records and hide gaps. What should be done?",
    options: [
      { id: "A", text: "Follow the manager because audit score matters" },
      { id: "B", text: "Provide accurate records and escalate the instruction through proper channels" },
      { id: "C", text: "Create new records after audit starts" },
      { id: "D", text: "Cancel the audit" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q39",
    number: 39,
    level: "L3",
    question: "Which combination best supports circular economy in manufacturing?",
    options: [
      { id: "A", text: "Use, discard and replace" },
      { id: "B", text: "Reduce, reuse, repair, recycle and recover materials" },
      { id: "C", text: "Store all scrap permanently" },
      { id: "D", text: "Increase packaging for every shipment" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q40",
    number: 40,
    level: "L3",
    question: "A plant meets internal ESG targets but violates a local environmental consent condition. How should this be assessed?",
    options: [
      { id: "A", text: "Acceptable because internal target is met" },
      { id: "B", text: "A compliance failure that requires immediate corrective action" },
      { id: "C", text: "Only a branding issue" },
      { id: "D", text: "Not relevant to ESG" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q41",
    number: 41,
    level: "L3",
    question: "Which activity is most likely to reduce Scope 2 emissions?",
    options: [
      { id: "A", text: "Switching to renewable electricity" },
      { id: "B", text: "Increasing diesel generator use" },
      { id: "C", text: "Using more company vehicles" },
      { id: "D", text: "Changing office furniture" },
    ],
    correctOptionId: "A",
  },
  {
    id: "q42",
    number: 42,
    level: "L3",
    question: "A high-performing supervisor regularly shouts at operators and discourages reporting problems. What is the ESG risk?",
    options: [
      { id: "A", text: "No risk because output is high" },
      { id: "B", text: "Toxic work culture, low psychological safety and possible human rights concern" },
      { id: "C", text: "Only a training calendar issue" },
      { id: "D", text: "Only a maintenance issue" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q43",
    number: 43,
    level: "L3",
    question: "Which evidence is strongest for proving ESG performance improvement?",
    options: [
      { id: "A", text: "A verbal claim by one employee" },
      { id: "B", text: "A poster displayed in the plant" },
      { id: "C", text: "Measured baseline, target, action plan, verified data and review records" },
      { id: "D", text: "A single photograph after cleaning" },
    ],
    correctOptionId: "C",
  },
  {
    id: "q44",
    number: 44,
    level: "L3",
    question: "A water recycling system is installed, but treated water quality is not monitored. What is the key risk?",
    options: [
      { id: "A", text: "The system may look unattractive" },
      { id: "B", text: "Reuse may create health, process or compliance risk" },
      { id: "C", text: "It will reduce reporting work" },
      { id: "D", text: "It will automatically improve biodiversity" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q45",
    number: 45,
    level: "L3",
    question: "Which situation indicates poor board or senior leadership oversight of ESG?",
    options: [
      { id: "A", text: "Regular review of ESG risks" },
      { id: "B", text: "Defined accountability for ESG KPIs" },
      { id: "C", text: "No review of material ESG risks or compliance gaps" },
      { id: "D", text: "Independent audit of ESG data" },
    ],
    correctOptionId: "C",
  },
  {
    id: "q46",
    number: 46,
    level: "L3",
    question: "An employee with a disability needs a reasonable workplace adjustment. What is the best ESG-aligned response?",
    options: [
      { id: "A", text: "Reject the request to keep rules same for all" },
      { id: "B", text: "Assess the request and provide reasonable accommodation where feasible" },
      { id: "C", text: "Transfer the employee without discussion" },
      { id: "D", text: "Ask the employee to manage without support" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q47",
    number: 47,
    level: "L3",
    question: "Which option best represents the waste hierarchy?",
    options: [
      { id: "A", text: "Dispose first, reuse later" },
      { id: "B", text: "Prevent, reduce, reuse, recycle, recover, dispose" },
      { id: "C", text: "Mix, store, burn, dispose" },
      { id: "D", text: "Buy, use, throw" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q48",
    number: 48,
    level: "L3",
    question: "A conflict of interest was disclosed before a decision and the person was removed from the approval process. What does this show?",
    options: [
      { id: "A", text: "Weak governance" },
      { id: "B", text: "Proper conflict management" },
      { id: "C", text: "Poor teamwork" },
      { id: "D", text: "Low productivity" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q49",
    number: 49,
    level: "L3",
    question: "A company offsets emissions but does not reduce its own energy use or process emissions. What is the main ESG concern?",
    options: [
      { id: "A", text: "Offsets are always illegal" },
      { id: "B", text: "Over-reliance on offsets instead of actual reduction" },
      { id: "C", text: "Water consumption will become zero" },
      { id: "D", text: "Governance is not relevant" },
    ],
    correctOptionId: "B",
  },
  {
    id: "q50",
    number: 50,
    level: "L3",
    question: "A contractor has repeated safety violations, but the project team wants to continue because stopping work will delay the schedule. What is the best decision?",
    options: [
      { id: "A", text: "Continue and close the issue after project completion" },
      { id: "B", text: "Stop or restrict work as per procedure, require corrective action, and review contractor suitability" },
      { id: "C", text: "Ignore because contractor safety is not company responsibility" },
      { id: "D", text: "Ask workers to sign a waiver" },
    ],
    correctOptionId: "B",
  },
];

export const TOTAL_QUESTIONS = QUIZ_QUESTIONS.length;

export function getQuestion(id: string): QuizQuestion | undefined {
  return QUIZ_QUESTIONS.find((q) => q.id === id);
}
